services:
  postgres_infracciones:
    image: postgres:16
    container_name: postgres_infracciones
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_infracciones_data:/var/lib/postgresql/data

volumes:
  postgres_infracciones_data:
