export const ROLES = {
  ADMIN: 'ADMIN',
  SECCION_PRIMERA: 'SECCION_PRIMERA',
  INFRACCIONES: 'INFRACCIONES',
  LIBERACIONES: 'LIBERACIONES',
  ENCIERRO: 'ENCIERRO',
  CONSULTA: 'CONSULTA',
  OPERADOR: 'OPERADOR',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const READ_ROLES: RoleName[] = [
  ROLES.ADMIN,
  ROLES.SECCION_PRIMERA,
  ROLES.INFRACCIONES,
  ROLES.LIBERACIONES,
  ROLES.ENCIERRO,
  ROLES.CONSULTA,
  ROLES.OPERADOR,
];

export const WRITE_ROLES: RoleName[] = [
  ROLES.ADMIN,
  ROLES.SECCION_PRIMERA,
  ROLES.INFRACCIONES,
  ROLES.LIBERACIONES,
  ROLES.ENCIERRO,
  ROLES.OPERADOR,
];
