export const APP_ROLES = {
  ADMIN: 'ADMIN',
  SECCION_PRIMERA: 'SECCION_PRIMERA',
  INFRACCIONES: 'INFRACCIONES',
  LIBERACIONES: 'LIBERACIONES',
  ENCIERRO: 'ENCIERRO',
  CONSULTA: 'CONSULTA',
  OPERADOR: 'OPERADOR',
} as const;
