export type PageKey =
  | 'dashboard'
  | 'infracciones'
  | 'nueva-infraccion'
  | 'pago'
  | 'liberacion'
  | 'retencion'
  | 'salida'
  | 'encierros-vehiculos'
  | 'flujo-operativo'
  | 'reportes-infracciones'
  | 'usuarios'
  | 'admin-expedientes'
  | 'admin-operaciones'
  | 'importaciones'
  | 'catalogos';
