export const ACCION_MOVIMIENTO = {
  INFRACCION_CAPTURADA: 'INFRACCION_CAPTURADA',
  PAGO_REGISTRADO: 'PAGO_REGISTRADO',
  LIBERACION_GENERADA: 'LIBERACION_GENERADA',
  VEHICULO_ENTREGADO: 'VEHICULO_ENTREGADO',
} as const;

export type AccionMovimientoNombre =
  (typeof ACCION_MOVIMIENTO)[keyof typeof ACCION_MOVIMIENTO];
