export const ESTADO_OPERATIVO_VEHICULO = {
  SIN_RETENCION: 'SIN_RETENCION',
  EN_ENCIERRO_SIN_PAGO: 'EN_ENCIERRO_SIN_PAGO',
  PAGADO_PENDIENTE_LIBERACION: 'PAGADO_PENDIENTE_LIBERACION',
  LIBERADO_PENDIENTE_SALIDA: 'LIBERADO_PENDIENTE_SALIDA',
  VEHICULO_ENTREGADO: 'VEHICULO_ENTREGADO',
} as const;

export type EstadoOperativoVehiculo =
  (typeof ESTADO_OPERATIVO_VEHICULO)[keyof typeof ESTADO_OPERATIVO_VEHICULO];

export const ESTADOS_OPERATIVOS_VEHICULO = Object.values(
  ESTADO_OPERATIVO_VEHICULO,
) as EstadoOperativoVehiculo[];
