export const ESTATUS_INFRACCION = {
  PAGADA: 'PAGADA',
  PAGADA_SIN_RETENCION: 'PAGADA_SIN_RETENCION',
  SOLVENTADA_SIN_PAGO: 'SOLVENTADA_SIN_PAGO',
  LIBERACION_GENERADA: 'LIBERACION_GENERADA',
  VEHICULO_ENTREGADO: 'VEHICULO_ENTREGADO',
} as const;

export type EstatusInfraccionNombre =
  (typeof ESTATUS_INFRACCION)[keyof typeof ESTATUS_INFRACCION];
